import React from "react";

export default function About() {
    return (
        <section className="w-full lg:w-3/4 px-4 mx-auto mt-10">
            <h1 className="text-4xl font-bold dark:text-white">About</h1>
            <hr className="w-full border border-gray-600"/>
            <p className="font-light text-base italic my-4 dark:text-gray-400">Lorem ipsum dolor sit amet consectetur adipisicing elit. In obcaecati corporis maiores reprehenderit quos eos, quae soluta ducimus quibusdam facere, facilis esse, sed labore eaque incidunt? Ipsum, facilis voluptas vel optio quo officiis. Fuga enim pariatur magni impedit consequatur atque quaerat porro quibusdam, unde harum consectetur asperiores in dolore corporis magnam quos ab at officia nisi dicta animi. Numquam maxime repellat harum deleniti, recusandae tempore provident ipsa reiciendis officiis placeat earum. Eos alias esse ipsam atque doloremque laborum porro tempore aperiam nam! Possimus labore inventore rem id, soluta modi, sed molestias in cum ullam, ab totam officia beatae expedita quas placeat veniam praesentium. Cum dolorum, unde doloribus sit quisquam atque! Consequatur eveniet incidunt accusamus id doloribus maiores fugit ducimus odit dolorem? Ipsa, deserunt facilis! Ut quasi, ipsa provident est suscipit magnam expedita earum harum optio et blanditiis, hic impedit ea assumenda. Quis consectetur, aliquam, beatae numquam fugit corrupti velit minima corporis suscipit, dignissimos qui debitis! Harum, itaque reprehenderit architecto voluptatum, porro sunt numquam illum maxime excepturi laudantium non necessitatibus consectetur, adipisci accusantium quos dolore repudiandae modi dolorum? Reprehenderit nesciunt quasi quo. Fugiat iure quibusdam necessitatibus, fugit obcaecati deserunt consequuntur hic quidem veniam nam pariatur placeat tempore architecto dicta explicabo et, possimus ab mollitia sint minus sapiente. Incidunt beatae voluptates illum eius quisquam laboriosam consectetur repudiandae sequi sapiente amet voluptate, ad similique fugit veritatis magni architecto! Ipsa minima nisi quae quos id. Perspiciatis expedita nesciunt voluptates quas enim doloribus culpa repudiandae earum laudantium nam. Molestias id quam nemo maiores cumque adipisci fugit dolore dolores quaerat qui, cum ex eos soluta fuga nisi possimus! Exercitationem aliquid sapiente earum? Modi, veniam iure facilis enim quam cumque obcaecati ad quod perspiciatis recusandae. Molestias facere qui esse totam eaque temporibus ea repellendus laboriosam deserunt quisquam non dolorem labore necessitatibus sit laborum nam, odit quibusdam voluptas!</p>
        </section>
    )
}